# Generated by Django 4.1.2 on 2022-10-11 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_class'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Class',
            new_name='School_Class',
        ),
    ]
