# Generated by Django 4.1.2 on 2022-10-11 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_rename_class_school_class'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='School_Class',
            new_name='Lecture',
        ),
    ]
